## YAML Template.
---
server:
  port: 9090
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: false
        use_sql_comments: false
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/e-booking?useSSL=false&characterEncoding=utf-8&useUnicode=true
    username: username
    password: password
logging:
  level:
    org:
      springframework: INFO
    ss:
      martin: DEBUG
platform:
  # system email settings
  systemEmailContactName: Platform support
  systemEmailContactEmail: platform.support@domain.com
  # super admin registration info
  superAdminEmail: superadmin@domain.com
  superAdminFirstName: Jack
  superAdminLastName: Hubert
  superAdminPassword: password
  # domain settings
  serverDomain: http://localhost:3000
  # mailjet settings
  mailjetApiKey: 492d0272c772703cf12e9557857b9947
  mailjetSecretKey: d1808011418953c5f357a2d6a5886fee
